### ISSUE TITLE
Borders not respecting geometry height

### ISSUE THREAD

**Issue by iNety** [gavinlaking/vedeu#117]
When running [borders_app.rb](https://github.com/gavinlaking/vedeu/blob/master/examples/borders_app.rb) I see
```
┌─────┐
└─────┘
```
rather than 

```
┌─────┐
│ on  │
└─────┘
```

here are the relevant lines from borders_app.rb:

```
  interface 'default_border' do
    border do
    end
    geometry do
      x      2
      y      2
      height 3
      width  7
    end
    colour  foreground: '#ffffff', background: '#ff0000'
  end

  renders do
    view('default_border') do
      lines do
        line 'on'
      end
    end
  end
```

I should note that without `border do end` it works just fine.

**Comment by gavinlaking** [comment]
Sorry for the inconvenience, it looks like I've broken it slightly!

I'll take a look at this and update shortly with progress.

Thanks for letting me know :+1:

**Comment by gavinlaking** [comment]
I think the fastest fix is to define the borders on the views themselves. Going forward, I'd like to separate borders from their interfaces so they can be defined on the interface or view, updated, shown and hidden independently.
