### ISSUE TITLE
Support for functional end-to-end testing

### ISSUE THREAD

**Issue by tristil** [gavinlaking/vedeu#156]
I don't consider this very high-priority but putting this here to demonstrate a use-case.

In a Curses-based app (https://github.com/tristil/minder) I wanted to use Aruba (https://github.com/tristil/minder) in order to do an end-to-end test along the lines of: start the app, verify that the screen is correct, press a button, verify the next state is correct. I got part of the way along with this to where I had a string from the program that I could check against an expectation.

The problem I ran into is that by running the Curses-based program, even in a subprocess, you're sending instructions to the screen to draw over everything, the result being that the failed expectation is never shown. Like, you run the test and the next line lists a success or failure but the details of the failure in between are clobbered by Curses.

As I write this I'm thinking of various workarounds (maybe logging the failed expectation or somehow driving another terminal window/tmux pane) but the point is that one of the things I like about Vedeu is that it doesn't hardcode STDOUT, so it should be possible to write everything out to a file instead. In that case it might be nice to have a different renderer that would represent screen changes as sequential states in the file, like:

```
State 1:
--- 
Do you like green eggs and ham? y/n
State 2:
---
I'm sorry to hear that.
```

Then you would have rspec matchers that work with this file format.

Anyway I know this is probably far out of scope of what you're working on but wanted to put this concept out there.

**Comment by gavinlaking** [comment]
Hi,

Thanks for the input :-)

I ran into this very same problem with Aruba- and it prompted me to write the DRb parts of Vedeu. The main struggle for me was sending input to the running process or subprocess and then asserting change from the output. Another area which helps here is the 'output/renderers' section of the code; here I can send the output in whatever form I might want and then assert on that.

To get the sequential states of the running app, I think it would just be a case of modifying the Renderers::File to write to a different file each time (perhaps using a timestamp as part of the filename). There are more elegant ways I'm sure.

Definitely worth more investigation!

Gav

**Comment by tristil** [comment]
Awesome. It sounds like the elements for what I want to do might already be there, and it's just a matter of writing up some docs and maybe bundling setup steps into rspec matchers. The sequential state file thing might end up being useful, but I'm not sure it's strictly necessary for making assertions. Anyway I'll be looking into this. Thanks for the direction.
