### ISSUE TITLE
Use the binding of a View in `template_for`

### ISSUE THREAD

**Issue by tristil** [gavinlaking/vedeu#175]
Instead of passing an object from the Controller to the View to the Template would it make sense to just pass the binding of the view to the template? 

This is what my current code looks like: https://github.com/tristil/minder/blob/migrate_to_vedeu/lib/minder/cli2/app/views/pomodoro.rb#L11 and https://github.com/tristil/minder/blob/migrate_to_vedeu/lib/minder/cli2/app/views/templates/pomodoro.erb Notice how I have to call `object.task_runner.blah` in the template instead of just `task_runner.blah`. My views usually deal with these two objects.

In general I'm not clear on the difference in role between the Controller and the View in Vedeu. One way to divide things would be to say that the controller gathers data (e.g. from a database) and the view (by convention) only does presentation-related transformations. In this case https://github.com/tristil/minder/blob/migrate_to_vedeu/lib/minder/cli2/app/views/pomodoro.rb#L25 would be an example of a transformation that should be directly available to the template.  FWIW I think this is how views are implemented in Lotus: https://github.com/lotus/view

**Comment by gavinlaking** [comment]
Hi,

I think the work being done below belongs in the view class; as this transformation is setting up state for the view itself. As you rightfully say, the controller gathers the data and the view doing only presentation-related transformations.

```
pomodoro_runner.pomodoros_today.map do |pomodoro|
  "\xF0\x9F\x8D\x85 "
end.join
```

I was using `object` to demonstrate some model data being passed into the view; one is obviously not tied to using that variable name as you can tell from the `.render` method in the controller. However, I have made the method signature only provide one object in the render class method and initialize method, which should probably be `(*args, options = {}, &block)` for maximum versatility.

What do you think?

**Comment by tristil** [comment]
Yeah, I think it should work like the render call in `Rails`, `render(:show, object1: 'blah', object2: 'blah2')` so that `object1` and `object2` are available in the template. I still think it might be cleaner if the template just used the view context as a binding, so that you would just have access to `pomodoros` in the template without doing anything, but being able to pass in options is good enough for me.

**Comment by gavinlaking** [comment]
I think one of the downsides of using the view context as a binding is that we're back in the situation which the DSL suffers from: the context changes depending on how/where it was called. At least with a explicit passing of variables to the view we can be sure that they are available at run time.

I'm starting to fear blocks and bindings again because of their implicit behaviour makes them 'unpredictable'.

**Comment by tristil** [comment]
:+1: That's a good argument. Having to explicitly pass in values is the most straight-forward and understandable approach.
