### ISSUE TITLE
minitest-reporters

### ISSUE THREAD

**Issue by shevegen** [gavinlaking/vedeu#213]
fatal: Not a git repository (or any of the parent directories): .gitCould not find gem 'minitest-reporters (= 1.0.19) ruby' in any of the gem sources listed in your Gemfile or available on this machine.Run `bundle install` to install missing gems.

Could the requirement be changed from = 1.0.19 to >= 1.0.19?

The latest one is 1.0.20, I believe it would work.

**Comment by gavinlaking** [comment]
Thanks for the heads up, sorry for the inconvenience!
