### ISSUE TITLE
Edited text dissappears in example editor_app.rb 

### ISSUE THREAD

**Issue by fwolfst** [gavinlaking/vedeu#241]
On a ubuntu 14.04 with zsh in an LXTerminal, the `test/support/examples/editor_app.rb` does not to seem as intended. Text entered is only sometimes visible for a tiny (miliseconds?) amount of time.

**Comment by gavinlaking** [comment]
Thanks for the bug report. This should now be fixed in release_0.6.21 (df9016e4bb7b28af7b589789cb2c72851898ef68).
