### ISSUE TITLE
Text editor feels slow/lags and eats keystrokes in examples/editor_app.rb

### ISSUE THREAD

**Issue by fwolfst** [gavinlaking/vedeu#243]
As a follow-up to #241 , which I confirm being fixed, now the terminal visibly flushes after every keypress and I can see the entered text.
But it feels as if this (flushing) takes so long that fluid text entry is not really possible, I consciously have to wait between keypresses.

The situation improves when removing the `debug` and `log` statements from the `configure` block, but still then during text-entry some keypresses are "eaten".

**Comment by gavinlaking** [comment]
I think the overall performance of Vedeu has improved since #248, so I'm going to close this issue for now.

**Comment by fwolfst** [comment]
Its definately better, but still skips a letter once a sentence. It feels as if the skips would occur more often the longer the text gets, btw.
