### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by KINGSABRI** [gavinlaking/vedeu#260]
Hi, it's first time to see your project, keep it up folks,

There is a simple porgramatic error in your example in [line 75](https://github.com/gavinlaking/vedeu/blob/master/examples/hello_worlds.rb#L75)

It should be
```ruby
line { centre "#{Vedeu.trigger(:_cursor_position_, Vedeu.focus)}" }
```

thanks

**Comment by gavinlaking** [comment]
Great spot! I'll be more careful in code review next time. :+1
