### ISSUE TITLE
How do I right align an interface?

### ISSUE THREAD

**Issue by net** [gavinlaking/vedeu#264]
I can do
```ruby
geometry do
    centred!
end
```
(centered is misspelled by the way) but what if I want to align an interface to the right of the screen?

**Comment by gavinlaking** [comment]
If you know the width of the interface, you could set `xn: Vedeu.width`, then `x: Vedeu.width - desired_width`. I think it'd be nicer to have a `right!`. There is an alias (afaik), so you can use either `centred!` or `centered!`.

Gav

**Comment by gavinlaking** [comment]
Hi,

It is now possible to align an interface to the left, centre or right from the Geometry::DSL (https://github.com/gavinlaking/vedeu/blob/master/lib/vedeu/geometry/dsl.rb#L117) (Yard hasn't updated yet as this has only just been pushed.).

Hope that helps!

Gav

**Comment by net** [comment]
Awesome, thanks! A couple questions. Is it possible to hide the cursor? None of the methods I found on the docs worked (I'm on OS X). Can I set the background color of the entire app? Also I’m not sure if this is a bug but setting the background color of the interface doesn’t set the background color of lines (lines seem to overwrite the background color by simply not having a background at all).

**Comment by gavinlaking** [comment]
Hi,

I think you've found a possible future feature (settings the colour of the entire app) and a few bugs. Sheepishly, I'm sure at some point recently lines would inherit the colour of the interface if a colour was not specifically set for the line. Likewise, hiding a cursor normally occurs on a per interface basis with `no_cursor!` (https://github.com/gavinlaking/vedeu/blob/master/lib/vedeu/interfaces/dsl.rb#L221), but a quick investigation shows this is broken (sorry!).

The best I can do at the moment is create a some issues here at the moment with your findings and gradually implement or fix each one.

My apologies for the inconvenience. Please raise more issues as you encounter them if you continue to use Vedeu.

Gav
