### ISSUE TITLE
Documentation of menu lacks a working example (DSL)

### ISSUE THREAD

**Issue by fwolfst** [gavinlaking/vedeu#275]
I tried to use menus with the 'dsl style' and failed horribly so.

It is unclear where the `menu` call has to be placed in order to be rendered correctly, I tried within an `interface`, a `view`, a `menus` block, etcpp. to no avail.

Best (for me anyways :) ) would be to have a simple example in the `examples` folder. I am willing to contribute one, based on a minimal example given in this issue.

**Comment by NullVoxPopuli** [comment]
I've gotten this far:

https://github.com/NullVoxPopuli/spiced_rumby/commit/41b2031d56e9e21d09451a92d11b950d2657008a

Currently I'm having issues binding keys to triggers.
`[error]  no implicit conversion of Symbol into Hash`

https://github.com/NullVoxPopuli/spiced_rumby/commit/41b2031d56e9e21d09451a92d11b950d2657008a#diff-13342a7b36fba46a5e505dff2e98d4e4R6

**Comment by fwolfst** [comment]
Any news? I just need the three or four correct lines and will propose a tiny example script and (maybe) as a goodie the bits of documentation - but the later I cannot promise.

**Comment by gavinlaking** [comment]
Hi,

My apologies for not providing this sooner, I had started working on it and then ran out of time, so picked it up again tonight to finish off. The branch `spike/file_browser` (https://github.com/gavinlaking/vedeu/compare/spike/file_browser) has a working (but not awesome) example. I've pushed this branch so you can continue, and in the meantime I'll tidy it up and get it merged into the master branch at some point shortly along with a bit more documentation. Hopefully it makes sense, but if you have any questions, please give me a shout. :smile:

**Comment by fwolfst** [comment]
Awesome, thanks. Lets see where this gets me.

**Comment by fwolfst** [comment]
Okay, get it. Although I have to say, that the example goes a bit beyond what I would have thought to be "DSL-ish".

Maybe I can put some pseudo-code of how I would like to use it.

```
Vedeu.interface :files_list_box do
  border do
    colour foreground: '#bbb', background: :default
    title 'File List'
  end
  geometry do
    # ...
  end
  use_default_menu_keymap!
  on_menu_select_trigger(:file_selected, :file_menu)

  Vedeu.views.do
    view :file_menu do
      menu(:file_menu) do
        items = Files.new('/tmp').all_files
        item_label_func = :to_s
        item_selected_line_func { |i| "= #{i.call(:item_label_func)}" }
        item_highlighted_line_func { |i| "> #{i.call(:item_label_func)}" }
      end
    end
  end
end

Vedeu.interface :file_content_box do
  # ....
  Vedeu.event_listener do
    on(:file_selected, :file) do
      # update/rerender with given file object
    end
  end
end

Vedeu.event_listener(:_global_) do
  on(:file_selected, :file) do
    log("Argument: #{file} is same as #{selected_menu_item(:file_menu)}")
  end
end
```

**Comment by gavinlaking** [comment]
There's some nice ideas in there which I don't think would be too much work to implement. Would you like to open a pull request with the start and perhaps we can build upon it from there?
