### ISSUE TITLE
How do I make something that allows general text input?

### ISSUE THREAD

**Issue by NullVoxPopuli** [gavinlaking/vedeu#278]
I'm writing a chat program over at https://github.com/NullVoxPopuli/spiced_rumby/tree/vedeu/lib/spiced_rumby/gui

and haven't seen / found any examples using text input. 

thanks!

**Comment by NullVoxPopuli** [comment]
@gavinlaking I saw your commit with the documentation on the different modes. :-)

I should clarify though - I want to have a text box, and have the contents of the textbox submitted upon hitting 'enter'.

Is there something in the docs that could elude as to how to do that?

**Comment by gavinlaking** [comment]
Hi @NullVoxPopuli 

I've done a little bit of work around the editor/input area of Vedeu and provided a simple example application to help document this. If you have any further questions, please give me a shout.

I'm going to close this issue shortly as I release a new version of Vedeu which includes these changes.

Hope they help, and thanks for using Vedeu. :-D

Gav

**Comment by NullVoxPopuli** [comment]
hi @gavinlaking, thanks for the example! :-)

I'm having an issue though:
it seems that `Vedeu.bind(:_command_)` isn't working for me, or isn't configured correctly.

This is how I'm using it:

usage of _command_ https://github.com/NullVoxPopuli/spiced_rumby/blob/vedeu/lib/spiced_rumby/gui/application.rb#L16

view: https://github.com/NullVoxPopuli/spiced_rumby/blob/vedeu/lib/spiced_rumby/gui/views/input.rb
interface: https://github.com/NullVoxPopuli/spiced_rumby/blob/vedeu/lib/spiced_rumby/gui/views/interfaces/input.rb
keybindings: https://github.com/NullVoxPopuli/spiced_rumby/blob/vedeu/lib/spiced_rumby/gui/models/keymaps/input.rb

controller / render: https://github.com/NullVoxPopuli/spiced_rumby/blob/vedeu/lib/spiced_rumby/gui/controllers/chat_controller.rb

**Comment by fwolfst** [comment]
Thanks Gavin,

@NullVoxPopuli it does somewhat work for me, iiuc the event is not called `_command_`, but `_editor_execute`:

```
  Vedeu.bind(:_editor_execute_) do |data|
    # assumed data would be entered text, which it is not
    $EVIL_GLOBAL = data.split.count # Fails, Symbol:split undefined
  end
```

But data contains the symbol given in the event trigger (`:editor_view`), which is fine but now I want to access the text entered.

**Comment by NullVoxPopuli** [comment]
It seems I'm having an issue before my binding is even triggered.

Hitting enter doesn't submit the text.

Also, I don't know what changed between computers, but now only every other letter is captured.

So, if I type 'hello there' only 'hll tee' shows up. :-\

this is my keybinding: 
```ruby
Vedeu.keymap :input do
  key(:enter) { Vedeu.trigger(:_editor_execute_, :input) }
end
```

**Comment by NullVoxPopuli** [comment]
ok, so the every other letter thing just appears to be because the VM i'm running this on isn't fast enough to capture all the input? o.o
Not sure what's up with that, I have 4 processors and 10 gigs of ram dedicated to it. :-\

**Comment by NullVoxPopuli** [comment]
ok, turns out the keymap wasn't being included. ha.
But, now I'm with @fwolfst where I'd like to be able to get the text somehow. :-\

**Comment by NullVoxPopuli** [comment]
oh hey, it is the _command_ event. ha. looks like having the correct keymap solves this

**Comment by NullVoxPopuli** [comment]
now, I guess I gotta figure out why it's suuuuuuuuuuuuuper slow. 
like... it totally doesn't work to type in right now :-\
