### ISSUE TITLE
Is there a way to make a view or interface scrollable?

### ISSUE THREAD

**Issue by NullVoxPopuli** [gavinlaking/vedeu#282]
editable! can make things scrollable as you enter many lines of  text, but I'd like a view that is scrollable and *not* editable.

is there an option for this?

**Comment by gavinlaking** [comment]
Hi,

Filling a view with more data than it can present will cause the view to become scrollable, though you must define movement keys in either the respective interface keymap or the global keymap:

```
# replace '_global_' with the interface name; e.g. :my_interface
Vedeu.keymap('_global_') do
  key(:up)    { Vedeu.trigger(:_cursor_up_)    }
  key(:right) { Vedeu.trigger(:_cursor_right_) }
  key(:down)  { Vedeu.trigger(:_cursor_down_)  }
  key(:left)  { Vedeu.trigger(:_cursor_left_)  }
end
```

Is this what you have in mind, or do I need further details? :-)

Hope that helps.

**Comment by NullVoxPopuli** [comment]
that worked!
So now I'll need to add some logic to auto-scroll to keep the most recent chat message at the bottom. 

Unless there is a nice way to do that automagically? :-)

**Comment by gavinlaking** [comment]
There isn't at the moment a way to automagically do that, but I'll keep this issue open and see if I can put together some events to manipulate the viewport for each interface so that you can simply call those to scroll the content. :+1:

**Comment by NullVoxPopuli** [comment]
awesome. something like a "a scroll to the bottom, but not so far where there are blank lines" trigger would be great :-)

**Comment by gavinlaking** [comment]
I've implemented two new events to scroll to the top and to the bottom of the content for the interface currently in focus (though you can also specify an interface name as the example shows below.

As with all events, the `Vedeu.trigger(:_cursor_*_)` can be called from anywhere, so you are not limited to just using it in a keymap.

```
# replace '_global_' with the interface name; e.g. :my_interface
Vedeu.keymap('_global_') do
  key(:up)    { Vedeu.trigger(:_cursor_up_)     }
  key(:right) { Vedeu.trigger(:_cursor_right_)  }
  key(:down)  { Vedeu.trigger(:_cursor_down_)   }
  key(:left)  { Vedeu.trigger(:_cursor_left_)   }
  key(:home)  { Vedeu.trigger(:_cursor_top_)    }
  key(:end)   { Vedeu.trigger(:_cursor_bottom_, :some_interface) }
end
```

Hope this helps!

**Comment by NullVoxPopuli** [comment]
Hey, this is awesome! thanks for this! but it looks like the viewable text is off by one?

when scrolled to the bottom, I need to scroll one more down in order to see the last message.

I even reduced the height of my box to make sure. but maybe I'm missing something else?

**Comment by NullVoxPopuli** [comment]
false alarm. I think I just wasn't being patient enough. Maybe I need to move a refresh somewhere else

**Comment by gavinlaking** [comment]
Actually, I think it might be my implementation here that is not quite right- it first checks the back buffer to get a line count as this is what will be displayed on next refresh as you rightly assert; perhaps it should be on front buffer, for what is currently on screen? (https://github.com/gavinlaking/vedeu/blob/master/lib/vedeu/buffers/buffer.rb#L126)

**Comment by NullVoxPopuli** [comment]
maybe? I could try that out when I get home
