### ISSUE TITLE
API for requesting input from a view?

### ISSUE THREAD

**Issue by NullVoxPopuli** [gavinlaking/vedeu#306]
in vanilla ruby, you can just call `gets` wherever you need user input.
In my app, I've abstracted input getting to support different methods of interaction, see: 
[Requesting Input](https://github.com/NullVoxPopuli/meshchat/blob/master/lib/meshchat/cli.rb#L93)
default: [Base Input Class](https://github.com/NullVoxPopuli/meshchat/blob/master/lib/meshchat/cli/base.rb#L8)
extended bash: [Sub Class](https://github.com/NullVoxPopuli/spiced_rumby/blob/master/lib/spiced_rumby/debug/cli_input.rb#L13)

Is there a way to do this with vedeu? or would it make more sense to have the UI be responsible for asking when the underlying logic needs data? -- I kinda don't like the second option, because it means that the UI needs to know about that underlying logic.

Thoughts?

**Comment by NullVoxPopuli** [comment]
For reference, I have these abstracted interfaces configurable via:
[GUI](https://github.com/NullVoxPopuli/spiced_rumby/blob/master/lib/spiced_rumby.rb#L36)
[Bash](https://github.com/NullVoxPopuli/spiced_rumby/blob/master/lib/spiced_rumby.rb#L26)

**Comment by gavinlaking** [comment]
If I understand you correctly, then you can 'get' the last keypress (in raw/fake mode) or collection of keys that were pressed (in cooked mode) by binding to the `:key` or `:command` events respectively:

```
Vedeu.bind(:key) do
   # ... do something with the key
end
```

or

```
Vedeu.bind(:command) do
  # ... do something with the command
end
```

Alternatively, if you can access input from the `Vedeu::Input::Store`, via the following API calls:

`Vedeu.all_commands` - returns an array of all commands received by Vedeu.
`Vedeu.all_keypresses` - returns an array of all keypresses received by Vedeu.
`Vedeu.last_command` - returns the last command entered into Vedeu.
`Vedeu.last_keypress` - returns the last keypress entered into Vedeu.

Hope that helps! :-)

**Comment by NullVoxPopuli** [comment]
ah ok. so I could track the input on `bind(:key)`, and reset it when the enter key is hit, and then my `get_input` method would just return the keys after get_input is called and before enter is pressed...
so -- get_input may need to be threaded. hmm

**Comment by NullVoxPopuli** [comment]
Vedeu.last_command looks to be kinda what I want..

but I think I'm having issues with logic here.

like, my brain is in the place of needing a `Vedeu.next_command` or something like that. ya know?

**Comment by gavinlaking** [comment]
Sorry for not getting back sooner, have been concentrating on a bit of tidy up.

As a suggestion, why not put together the feature you'd like in to a pull request. We can then both work on it (if needed). I'm sure that which you're asking isn't too tricky and you can rely mainly on copy and adapting code which is nearly all present.

Fancy the challenge?

Gav

**Comment by gavinlaking** [comment]
I've created a mechanism to directly read from the terminal, which I think is what you are looking for.

You can either provide the input yourself, so input can be faked programmatically, or provided by the user:

```
Vedeu.read("some input here") # => programmatic cooked mode (default)
Vedeu.read("\e[24;2~", mode: :raw) # => programmatic raw mode (provides :shift_f12 in this example)
Vedeu.read(nil, mode: :raw) #  => for a single keypress
Vedeu.read(nil, mode: :cooked) # => (default mode) for a 'line at a time' (pressing 'return' ends the line)
```

The way that these are used will depend on the mode your terminal is currently set to. Vedeu by default sets this to `:raw` (single character, hidden cursor). `Vedeu.read` by default expects the terminal to be in `:cooked` mode unless you provide the `mode: :raw` option.

- In `:cooked` mode (default), it will trigger a `:_command_` event with the input provided, meaning you should bind to `:command` to receive the input.
- In `:raw` mode, it will trigger a `:_keypress_` event with the input provided, meaning you should bind to `:key` to receive the input.

You can also access the input given using the API methods as outlined previously;

```
Vedeu.all_commands - returns an array of all commands received by Vedeu.
Vedeu.all_keypresses - returns an array of all keypresses received by Vedeu.
Vedeu.last_command - returns the last command entered into Vedeu.
Vedeu.last_keypress - returns the last keypress entered into Vedeu.
```

Hope that helps,

Gav

**Comment by NullVoxPopuli** [comment]
ooo, I'll try this out

**Comment by gavinlaking** [comment]
Cool :-) Let me know it you encounter any issues, and we'll try to iron them out.

**Comment by NullVoxPopuli** [comment]
I don't know if I'm understanding correctly, but here is what I did on this commit: https://github.com/NullVoxPopuli/spiced_rumby/commit/6b39e53afa95ec03b6cf293cd01c2c64f3d95a27#diff-2e3b83011d5e7025276efe562972b20b

<enter to get to chat screen>
/init
<enter> (it then promps me with a Y/N question)
Y (doesn't render)
<enter> (nothing happened)

```
[ 3.4483] [event]    Triggering: ':_command_' for "/init"
[ 3.4484] [info]     "/init"
[ 3.4485] [info]     String
[ 3.4488] [update]   warning: uid exists, are you sure you want a new identity? (Y/N)
[ 3.4489] [update]   num: 1
[ 3.4490] [event]    Triggering: ':_cursor_bottom_' for :chat
[ 3.4497] [update]   Vedeu::Cursors::Cursor: 'chat'
[ 3.4498] [event]    Triggering: ':_refresh_cursor_' for :chat
[ 3.4500] [output]   Refreshing cursor: 'chat' (x:2, y:2, ox:0, oy:0, visible:false)
[ 3.4503] [event]    Triggering: ':_clear_view_' for :chat
[ 3.4558] [timer]    Clearing interface: 'chat' took 5.398ms.
[ 3.4752] [render]   Rendering via Vedeu::Renderers::Terminal
[ 3.4775] [event]    Triggering: ':_hide_cursor_'
[ 3.4778] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.4779] [output]   Hiding cursor: 'input'
[ 3.5156] [compress] Compression: 5097 objects -> 47054 characters
[ 3.5157] [timer]    Compression for 5097 objects took 35.031ms.
[ 3.5161] [event]    Triggering: ':_show_cursor_'
[ 3.5162] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.5163] [output]   Showing cursor: 'input'
[ 3.5168] [event]    Triggering: ':_refresh_view_' for :chat
[ 3.5170] [event]    Triggering: ':_clear_view_content_' for :chat
[ 3.5185] [timer]    Optimised clearing content: 'chat' took 1.378ms.
[ 3.5253] [timer]    Clearing content: 'chat' took 6.577ms.
[ 3.5418] [event]    Triggering: ':_refresh_border_' for :chat
[ 3.5652] [timer]    Drawing border: 'chat' took 23.129ms.
[ 3.5666] [render]   Rendering via Vedeu::Renderers::Terminal
[ 3.5669] [event]    Triggering: ':_hide_cursor_'
[ 3.5670] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.5671] [output]   Hiding cursor: 'input'
[ 3.6023] [compress] Compression: 5097 objects -> 48422 characters
[ 3.6025] [timer]    Compression for 5097 objects took 32.693ms.
[ 3.6037] [event]    Triggering: ':_show_cursor_'
[ 3.6038] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.6038] [output]   Showing cursor: 'input'
[ 3.6046] [update]   Vedeu::Geometries::Geometry: 'chat'
[ 3.6048] [update]   Vedeu::Buffers::Buffer: 'chat'
[ 3.6049] [event]    Triggering: ':_refresh_view_' for :chat
[ 3.6050] [event]    Triggering: ':_clear_view_content_' for :chat
[ 3.6068] [timer]    Optimised clearing content: 'chat' took 1.586ms.
[ 3.6130] [timer]    Clearing content: 'chat' took 5.945ms.
[ 3.6290] [output]   Buffer swapping: 'chat'
[ 3.6291] [update]   Vedeu::Buffers::Buffer: 'chat'
[ 3.6297] [timer]    Rendering content: 'chat' took 0.45ms.
[ 3.6299] [render]   Rendering via Vedeu::Renderers::Terminal
[ 3.6306] [event]    Triggering: ':_hide_cursor_'
[ 3.6307] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.6307] [output]   Hiding cursor: 'input'
[ 3.6663] [compress] Compression: 5097 objects -> 48455 characters
[ 3.6679] [timer]    Compression for 5097 objects took 35.875ms.
[ 3.6693] [event]    Triggering: ':_show_cursor_'
[ 3.6694] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.6731] [output]   Showing cursor: 'input'
[ 3.6747] [event]    Triggering: ':_refresh_border_' for :chat
[ 3.6879] [timer]    Drawing border: 'chat' took 13.007ms.
[ 3.6900] [render]   Rendering via Vedeu::Renderers::Terminal
[ 3.6909] [event]    Triggering: ':_hide_cursor_'
[ 3.6911] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.6912] [output]   Hiding cursor: 'input'
[ 3.7197] [compress] Compression: 5097 objects -> 48455 characters
[ 3.7199] [timer]    Compression for 5097 objects took 26.358ms.
[ 3.7209] [event]    Triggering: ':_show_cursor_'
[ 3.7211] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.7212] [output]   Showing cursor: 'input'
[ 3.7222] [event]    Triggering: ':_menu_view_' for :contacts
[ 3.7232] [update]   Vedeu::Buffers::Buffer: 'contacts'
[ 3.7242] [event]    Triggering: ':_refresh_view_' for :contacts
[ 3.7244] [event]    Triggering: ':_clear_view_content_' for :contacts
[ 3.7267] [timer]    Optimised clearing content: 'contacts' took 1.302ms.
[ 3.7293] [timer]    Clearing content: 'contacts' took 1.416ms.
[ 3.7357] [output]   Buffer swapping: 'contacts'
[ 3.7367] [update]   Vedeu::Buffers::Buffer: 'contacts'
[ 3.7382] [timer]    Rendering content: 'contacts' took 0.512ms.
[ 3.7470] [render]   Rendering via Vedeu::Renderers::Terminal
[ 3.7487] [event]    Triggering: ':_hide_cursor_'
[ 3.7496] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.7504] [output]   Hiding cursor: 'input'
[ 3.7829] [compress] Compression: 5097 objects -> 48455 characters
[ 3.7840] [timer]    Compression for 5097 objects took 31.184ms.
[ 3.7870] [event]    Triggering: ':_show_cursor_'
[ 3.7880] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.7894] [output]   Showing cursor: 'input'
[ 3.7910] [event]    Triggering: ':_refresh_border_' for :contacts
[ 3.8009] [timer]    Drawing border: 'contacts' took 9.643ms.
[ 3.8019] [render]   Rendering via Vedeu::Renderers::Terminal
[ 3.8024] [event]    Triggering: ':_hide_cursor_'
[ 3.8025] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.8026] [output]   Hiding cursor: 'input'
[ 3.8338] [compress] Compression: 5097 objects -> 48455 characters
[ 3.8349] [timer]    Compression for 5097 objects took 30.465ms.
[ 3.8367] [event]    Triggering: ':_show_cursor_'
[ 3.8375] [update]   Vedeu::Cursors::Cursor: 'input'
[ 3.8383] [output]   Showing cursor: 'input'

```

**Comment by gavinlaking** [comment]
Just needed a little extra work. Simply upgrade to v0.6.67 of Vedeu, then change: `Vedeu.read(nil, mode: :cooked)` to `Vedeu.read(nil, mode: :fake)`. I used this to input `/init` then a `Y`, then when that succeeded, I tried `/exit` and that worked too. Hopefully that'll get you back running again.

Gav

**Comment by NullVoxPopuli** [comment]
woo! it works! thanks a ton!

Now, the only thing left to do with my little app is to actually do the message relaying between mesh nodes. :-)
