### ISSUE TITLE
Entire width not filled with background color?

### ISSUE THREAD

**Issue by NullVoxPopuli** [gavinlaking/vedeu#340]
Is there maybe a global background color to set that would affect everything? including this black bar on the right?

![image](https://cloud.githubusercontent.com/assets/199018/11673147/608ac824-9de4-11e5-8875-99089aa59e0d.png)

**Comment by NullVoxPopuli** [comment]
oops... that was supposed to just be the terminal. haha

**Comment by gavinlaking** [comment]
That's fine. :+1:

You can set a default background/foreground colour in the configuration:

```
Vedeu.configure do
  colour background: '#ff0000', foreground: '#ffff00' # hideous
  # ...
end
```

Or use `background` and/or `foreground` directly, depending on your needs. See: http://www.rubydoc.info/gems/vedeu/Vedeu/Config/API#background-instance_method and http://www.rubydoc.info/gems/vedeu/Vedeu/Config/API#foreground-instance_method or 
http://www.rubydoc.info/gems/vedeu/Vedeu/Config/API#colour-instance_method for more details.

Hope that helps.

**Comment by NullVoxPopuli** [comment]
I didn't know you could set color in configure. 

Are all colors available?

I tried this:
`background Colorer::BACKGROUND`
and that constant is `#222222`, but when rendered, it shows black.


when I used '#ff0000', I noticed that the views default to black (rather than inheriting, like in HTML/CSS)
![image](https://cloud.githubusercontent.com/assets/199018/11698691/0947c5a8-9e8e-11e5-990a-58a69b2f3c80.png)
- notice the red on the bottom (this is the top-level color)

**Comment by gavinlaking** [comment]
Does the interface in this example specify a colour? If it sets a background colour I'd expect that to override the terminal colour. (I'll check that though.).

**Comment by NullVoxPopuli** [comment]
when I took the above screen shot, neither the interface, nor the view had color set.

**Comment by gavinlaking** [comment]
Thanks :-) I'll investigate further and update with findings and fixes.

**Comment by gavinlaking** [comment]
Due to colour support in various terminals, setting '#222222' may render as black as this is the closest match for a terminal only supporting 256 colours. Work in #351 (version 0.8.5 (https://github.com/gavinlaking/vedeu/commit/d1059aa65ccfa3bf04373bbe62656b18b2dee1bf)) fixes the width/height issues you were seeing I think. Close this issue if you are happy it is fixed, otherwise please leave a comment and I'll try to address it in due course :smile:

**Comment by gavinlaking** [comment]
Closing this issue as I believe it to be fixed.
