### ISSUE TITLE
Alignment refactor broke examples.

### ISSUE THREAD

**Issue by gavinlaking** [gavinlaking/vedeu#361]
Courtesy of @ch1c0t:

Minor refactor to geometry/view alignment; (a38dd16) has broken a lot of the examples:

```bash
➜  vedeu git:(master) bundle exec ./examples/dsl_alignment.rb 
/home/home/ch1c0t/sources/ruby/aliens/vedeu/lib/vedeu/geometries/dsl/dsl.rb:98:in `align': wrong number of arguments (given 4, expected 0) (ArgumentError)
        from ./examples/dsl_alignment.rb:26:in `block (2 levels) in <class:AlignmentApp>'
        from /home/home/ch1c0t/sources/ruby/aliens/vedeu/lib/vedeu/repositories/model.rb:41:in `instance_eval'
        from /home/home/ch1c0t/sources/ruby/aliens/vedeu/lib/vedeu/repositories/model.rb:41:in `build'
        from /home/home/ch1c0t/sources/ruby/aliens/vedeu/lib/vedeu/dsl/geometry.rb:63:in `geometry'
        from ./examples/dsl_alignment.rb:25:in `block in <class:AlignmentApp>'
        from /home/home/ch1c0t/sources/ruby/aliens/vedeu/lib/vedeu/repositories/model.rb:41:in `instance_eval'
        from /home/home/ch1c0t/sources/ruby/aliens/vedeu/lib/vedeu/repositories/model.rb:41:in `build'
        from /home/home/ch1c0t/sources/ruby/aliens/vedeu/lib/vedeu/interfaces/dsl.rb:48:in `interface'
        from ./examples/dsl_alignment.rb:21:in `<class:AlignmentApp>'
        from ./examples/dsl_alignment.rb:8:in `<main>'
```

**Comment by gavinlaking** [comment]
My apologies for this. I'll put together a fix ASAP. Thank you for reporting it, I'll also make efforts to include the examples as part of the integration suite to prevent it happening again.

Thanks!

Gav

**Comment by ch1c0t** [comment]
Thank you for the quick fix.

You also might want to give a look to [mutant](https://github.com/mbj/mutant)(of course, only if time permits). The minitest integration is still in the works, but it helps in avoiding regressions impressively.

**Comment by gavinlaking** [comment]
Thanks for the heads up re: mutant and minitest (https://github.com/mbj/mutant/pull/445). I created a spike branch to have a play with this, but I'm getting a strange failure relating to `.cover_expression` which I don't fully understand. For the time being, I'll keep my eye on mutant as it could be really useful, and once the minitest feature branch is merged will have another go.
