### ISSUE TITLE
Win Compatibility:Temp Dir Path

### ISSUE THREAD

**Issue by romaslmd** [gavinlaking/vedeu#370]
Hi,
on Windows OS `vedeu new app_name`
Error:
> C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vedeu-0.8.21/lib/vedeu/logging/lockless_l
og_device.rb:69:in `initialize': No such file or directory @ rb_sysopen - /tmp/v
edeu_bootstrap.log (Errno::ENOENT)

Looks like on Win OS no such directory as `/tmp`

It looks like a good solution is to determine temp dir of OS using ruby library:
```
require 'tmpdir'
temp = Dir.tmpdir() 
```

**Comment by gavinlaking** [comment]
Hi,

Thanks for the suggestion/solution! I've updated all the `/tmp` instances throughout the codebase in an effort to fix this issue. Please let me know if I can be any further assistance in making Vedeu more compatible with Windows.

Gav
